{
 "title": "Server-PLEX SMART",
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "SATA1 Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_serial\" or r[\"_field\"] == \"disk_model\" or r[\"_field\"] == \"disk_status\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Current_Pending_Sector\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n|> last()\r\n  |> limit(n: 1)\r\n |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n |> group(columns: [\"_time\"], mode:\"by\")\r\n |> map(\r\n    fn: (r) => ({\r\n        r with\r\n            //////////////////////////\r\n            //Disk_Status value mapping\r\n            //////////////////////////\r\n            disk_status_converted: if r.disk_status == 1 then\r\n                \"Passed\"\r\n            else if r.disk_status == 2 then\r\n                \"Failed\"    \r\n            else\r\n                \"ERROR!!!!\",\r\n        }),\r\n    )\r\n  |> drop(columns: [\"_measurement\", \"_stop\", \"_start\", \"_time\", \"nas_name\", \"disk_path\", \"smart_attribute\",\"disk_status\"])\r\n  |> rename(columns: {disk_model: \"Model\", disk_serial: \"Serial\", disk_status_converted: \"Status\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "SATA2 Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 7, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_serial\" or r[\"_field\"] == \"disk_model\" or r[\"_field\"] == \"disk_status\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Current_Pending_Sector\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n|> last()\r\n  |> limit(n: 1)\r\n |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n |> group(columns: [\"_time\"], mode:\"by\")\r\n |> map(\r\n    fn: (r) => ({\r\n        r with\r\n            //////////////////////////\r\n            //Disk_Status value mapping\r\n            //////////////////////////\r\n            disk_status_converted: if r.disk_status == 1 then\r\n                \"Passed\"\r\n            else if r.disk_status == 2 then\r\n                \"Failed\"    \r\n            else\r\n                \"ERROR!!!!\",\r\n        }),\r\n    )\r\n  |> drop(columns: [\"_measurement\", \"_stop\", \"_start\", \"_time\", \"nas_name\", \"disk_path\", \"smart_attribute\",\"disk_status\"])\r\n  |> rename(columns: {disk_model: \"Model\", disk_serial: \"Serial\", disk_status_converted: \"Status\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "SATA3 Status",
   "type": "table",
   "gridPos": { "h": 4, "w": 7, "x": 14, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"disk_serial\" or r[\"_field\"] == \"disk_model\" or r[\"_field\"] == \"disk_status\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Current_Pending_Sector\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n|> last()\r\n  |> limit(n: 1)\r\n |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n |> group(columns: [\"_time\"], mode:\"by\")\r\n |> map(\r\n    fn: (r) => ({\r\n        r with\r\n            //////////////////////////\r\n            //Disk_Status value mapping\r\n            //////////////////////////\r\n            disk_status_converted: if r.disk_status == 1 then\r\n                \"Passed\"\r\n            else if r.disk_status == 2 then\r\n                \"Failed\"    \r\n            else\r\n                \"ERROR!!!!\",\r\n        }),\r\n    )\r\n  |> drop(columns: [\"_measurement\", \"_stop\", \"_start\", \"_time\", \"nas_name\", \"disk_path\", \"smart_attribute\",\"disk_status\"])\r\n  |> rename(columns: {disk_model: \"Model\", disk_serial: \"Serial\", disk_status_converted: \"Status\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "sata1",
   "type": "table",
   "gridPos": { "h": 27, "w": 10, "x": 0, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ID\" or r[\"_field\"] == \"RAW_value\" or r[\"_field\"] == \"current_value\" or r[\"_field\"] == \"threshold_value\" or r[\"_field\"] == \"worst_value\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Avg_Block-Erase_Count\" or r[\"smart_attribute\"] == \"Bckgnd_Program_Page_Cnt\" or r[\"smart_attribute\"] == \"Command_Timeout\" or r[\"smart_attribute\"] == \"Current_Pending_Sector\" or r[\"smart_attribute\"] == \"End-to-End_Error\" or r[\"smart_attribute\"] == \"Erase_Fail_Count\" or r[\"smart_attribute\"] == \"Hardware_ECC_Recovered\" or r[\"smart_attribute\"] == \"Host_Program_Page_Count\" or r[\"smart_attribute\"] == \"Offline_Uncorrectable\" or r[\"smart_attribute\"] == \"Percent_Lifetime_Remain\" or r[\"smart_attribute\"] == \"Power_Cycle_Count\" or r[\"smart_attribute\"] == \"Power_On_Hours\" or r[\"smart_attribute\"] == \"Program_Fail_Count\" or r[\"smart_attribute\"] == \"RAIN_Success_Recovered\" or r[\"smart_attribute\"] == \"Raw_Read_Error_Rate\" or r[\"smart_attribute\"] == \"Reallocated_Event_Count\" or r[\"smart_attribute\"] == \"Reallocated_Sector_Ct\" or r[\"smart_attribute\"] == \"Reported_Uncorrect\" or r[\"smart_attribute\"] == \"Reserved_Block_Pct\" or r[\"smart_attribute\"] == \"SATA_Int_Downshift_Ct\" or r[\"smart_attribute\"] == \"Temperature_Celsius\" or r[\"smart_attribute\"] == \"Total_LBAs_Written\" or r[\"smart_attribute\"] == \"UDMA_CRC_Error_Count\" or r[\"smart_attribute\"] == \"Unexpect_Power_Loss_Ct\" or r[\"smart_attribute\"] == \"Unused_Rsvd_Blk_Cnt_Tot\" or r[\"smart_attribute\"] == \"Write_Error_Rate\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> last()\r\n  |> limit(n: 1)\r\n |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n |> group(columns: [\"_time\"], mode:\"by\")\r\n  |> drop(columns: [\"_measurement\", \"_stop\", \"_start\", \"_time\", \"nas_name\", \"disk_path\"])\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "sata2",
   "type": "table",
   "gridPos": { "h": 27, "w": 10, "x": 10, "y": 4 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ID\" or r[\"_field\"] == \"RAW_value\" or r[\"_field\"] == \"current_value\" or r[\"_field\"] == \"threshold_value\" or r[\"_field\"] == \"worst_value\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Avg_Block-Erase_Count\" or r[\"smart_attribute\"] == \"Bckgnd_Program_Page_Cnt\" or r[\"smart_attribute\"] == \"Command_Timeout\" or r[\"smart_attribute\"] == \"Current_Pending_Sector\" or r[\"smart_attribute\"] == \"End-to-End_Error\" or r[\"smart_attribute\"] == \"Erase_Fail_Count\" or r[\"smart_attribute\"] == \"Hardware_ECC_Recovered\" or r[\"smart_attribute\"] == \"Host_Program_Page_Count\" or r[\"smart_attribute\"] == \"Offline_Uncorrectable\" or r[\"smart_attribute\"] == \"Percent_Lifetime_Remain\" or r[\"smart_attribute\"] == \"Power_Cycle_Count\" or r[\"smart_attribute\"] == \"Power_On_Hours\" or r[\"smart_attribute\"] == \"Program_Fail_Count\" or r[\"smart_attribute\"] == \"RAIN_Success_Recovered\" or r[\"smart_attribute\"] == \"Raw_Read_Error_Rate\" or r[\"smart_attribute\"] == \"Reallocated_Event_Count\" or r[\"smart_attribute\"] == \"Reallocated_Sector_Ct\" or r[\"smart_attribute\"] == \"Reported_Uncorrect\" or r[\"smart_attribute\"] == \"Reserved_Block_Pct\" or r[\"smart_attribute\"] == \"SATA_Int_Downshift_Ct\" or r[\"smart_attribute\"] == \"Temperature_Celsius\" or r[\"smart_attribute\"] == \"Total_LBAs_Written\" or r[\"smart_attribute\"] == \"UDMA_CRC_Error_Count\" or r[\"smart_attribute\"] == \"Unexpect_Power_Loss_Ct\" or r[\"smart_attribute\"] == \"Unused_Rsvd_Blk_Cnt_Tot\" or r[\"smart_attribute\"] == \"Write_Error_Rate\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> last()\r\n  |> limit(n: 1)\r\n |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n |> group(columns: [\"_time\"], mode:\"by\")\r\n  |> drop(columns: [\"_measurement\", \"_stop\", \"_start\", \"_time\", \"nas_name\", \"disk_path\"])\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "sata3",
   "type": "table",
   "gridPos": { "h": 27, "w": 10, "x": 5, "y": 31 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"ID\" or r[\"_field\"] == \"RAW_value\" or r[\"_field\"] == \"current_value\" or r[\"_field\"] == \"threshold_value\" or r[\"_field\"] == \"worst_value\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Avg_Block-Erase_Count\" or r[\"smart_attribute\"] == \"Bckgnd_Program_Page_Cnt\" or r[\"smart_attribute\"] == \"Command_Timeout\" or r[\"smart_attribute\"] == \"Current_Pending_Sector\" or r[\"smart_attribute\"] == \"End-to-End_Error\" or r[\"smart_attribute\"] == \"Erase_Fail_Count\" or r[\"smart_attribute\"] == \"Hardware_ECC_Recovered\" or r[\"smart_attribute\"] == \"Host_Program_Page_Count\" or r[\"smart_attribute\"] == \"Offline_Uncorrectable\" or r[\"smart_attribute\"] == \"Percent_Lifetime_Remain\" or r[\"smart_attribute\"] == \"Power_Cycle_Count\" or r[\"smart_attribute\"] == \"Power_On_Hours\" or r[\"smart_attribute\"] == \"Program_Fail_Count\" or r[\"smart_attribute\"] == \"RAIN_Success_Recovered\" or r[\"smart_attribute\"] == \"Raw_Read_Error_Rate\" or r[\"smart_attribute\"] == \"Reallocated_Event_Count\" or r[\"smart_attribute\"] == \"Reallocated_Sector_Ct\" or r[\"smart_attribute\"] == \"Reported_Uncorrect\" or r[\"smart_attribute\"] == \"Reserved_Block_Pct\" or r[\"smart_attribute\"] == \"SATA_Int_Downshift_Ct\" or r[\"smart_attribute\"] == \"Temperature_Celsius\" or r[\"smart_attribute\"] == \"Total_LBAs_Written\" or r[\"smart_attribute\"] == \"UDMA_CRC_Error_Count\" or r[\"smart_attribute\"] == \"Unexpect_Power_Loss_Ct\" or r[\"smart_attribute\"] == \"Unused_Rsvd_Blk_Cnt_Tot\" or r[\"smart_attribute\"] == \"Write_Error_Rate\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> last()\r\n  |> limit(n: 1)\r\n |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n |> group(columns: [\"_time\"], mode:\"by\")\r\n  |> drop(columns: [\"_measurement\", \"_stop\", \"_start\", \"_time\", \"nas_name\", \"disk_path\"])\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Life Remaining",
   "type": "timeseries",
   "description": "RAW value: This value is expressed as a percentage of the average erase count and the rated erase\ncount of the media, which is the percentage of lifetime used as opposed to the Current\nValue which is the percentage of lifetime remaining.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 58 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Percent_Lifetime_Remain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n   |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n    |> map(fn: (r) => ({r with sata1_percent_life_remain: (100.0 - r.RAW_value)}))\r\n    |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_field\", \"_start\", \"_stop\", \"RAW_value\"])\r\n    |> rename(columns: {sata1_percent_life_remain: \"SATA1 Percent Life Remaining\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Percent_Lifetime_Remain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n   |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n    |> map(fn: (r) => ({r with sata1_percent_life_remain: (100.0 - r.RAW_value)}))\r\n    |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_field\", \"_start\", \"_stop\", \"RAW_value\"])\r\n    |> rename(columns: {sata1_percent_life_remain: \"SATA2 Percent Life Remaining\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Percent_Lifetime_Remain\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n   |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n    |> map(fn: (r) => ({r with sata1_percent_life_remain: (100.0 - r.RAW_value)}))\r\n    |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_field\", \"_start\", \"_stop\", \"RAW_value\"])\r\n    |> rename(columns: {sata1_percent_life_remain: \"SATA3 Percent Life Remaining\"})\r\n  |> yield()"
    },
    {
     "query": "Reallocated_Sector_Ct=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Reallocated_Sector_Ct\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_start\", \"_stop\"])\r\n\r\n\r\nUnused_Rsvd_Blk_Cnt_Tot=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Unused_Rsvd_Blk_Cnt_Tot\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n    |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_start\", \"_stop\"])\r\n\r\njoin(tables: {Unused_Rsvd_Blk_Cnt_Tot: Unused_Rsvd_Blk_Cnt_Tot, Reallocated_Sector_Ct: Reallocated_Sector_Ct}, on: [\"_time\",\"_field\"])\r\n    |> map(fn: (r) => ({r with sata1_percent_life_remain: ((r._value_Unused_Rsvd_Blk_Cnt_Tot / (r._value_Unused_Rsvd_Blk_Cnt_Tot + r._value_Reallocated_Sector_Ct))*100.0)}))\r\n   |> drop(columns: [\"_field_Reallocated_Sector_Ct\",\"_field_Unused_Rsvd_Blk_Cnt_Tot\",\"_value_Reallocated_Sector_Ct\",\"_value_Unused_Rsvd_Blk_Cnt_Tot\", \"_field\"])\r\n   |> rename(columns: {sata1_percent_life_remain: \"SATA1 Reserved Block Remaining\"})\r\n  |> yield()"
    },
    {
     "query": "Reallocated_Sector_Ct=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Reallocated_Sector_Ct\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_start\", \"_stop\"])\r\n\r\n\r\nUnused_Rsvd_Blk_Cnt_Tot=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Unused_Rsvd_Blk_Cnt_Tot\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n    |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_start\", \"_stop\"])\r\n\r\njoin(tables: {Unused_Rsvd_Blk_Cnt_Tot: Unused_Rsvd_Blk_Cnt_Tot, Reallocated_Sector_Ct: Reallocated_Sector_Ct}, on: [\"_time\",\"_field\"])\r\n    |> map(fn: (r) => ({r with sata1_percent_life_remain: ((r._value_Unused_Rsvd_Blk_Cnt_Tot / (r._value_Unused_Rsvd_Blk_Cnt_Tot + r._value_Reallocated_Sector_Ct))*100.0)}))\r\n   |> drop(columns: [\"_field_Reallocated_Sector_Ct\",\"_field_Unused_Rsvd_Blk_Cnt_Tot\",\"_value_Reallocated_Sector_Ct\",\"_value_Unused_Rsvd_Blk_Cnt_Tot\", \"_field\"])\r\n   |> rename(columns: {sata1_percent_life_remain: \"SATA2 Reserved Block Remaining\"})\r\n  |> yield()"
    },
    {
     "query": "Reallocated_Sector_Ct=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Reallocated_Sector_Ct\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_start\", \"_stop\"])\r\n\r\n\r\nUnused_Rsvd_Blk_Cnt_Tot=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Unused_Rsvd_Blk_Cnt_Tot\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n    |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_start\", \"_stop\"])\r\n\r\njoin(tables: {Unused_Rsvd_Blk_Cnt_Tot: Unused_Rsvd_Blk_Cnt_Tot, Reallocated_Sector_Ct: Reallocated_Sector_Ct}, on: [\"_time\",\"_field\"])\r\n    |> map(fn: (r) => ({r with sata1_percent_life_remain: ((r._value_Unused_Rsvd_Blk_Cnt_Tot / (r._value_Unused_Rsvd_Blk_Cnt_Tot + r._value_Reallocated_Sector_Ct))*100.0)}))\r\n   |> drop(columns: [\"_field_Reallocated_Sector_Ct\",\"_field_Unused_Rsvd_Blk_Cnt_Tot\",\"_value_Reallocated_Sector_Ct\",\"_value_Unused_Rsvd_Blk_Cnt_Tot\", \"_field\"])\r\n   |> rename(columns: {sata1_percent_life_remain: \"SATA3 Reserved Block Remaining\"})\r\n  |> yield()"
    },
    {
     "query": "//Micron ECO 5200 1.92TB SSD is rated for 3.5PB of write endurance @ 512-bit sectors\r\n//SSD data sheet found here: https://www.micron.com/solutions/technical-briefs/micron-5200-series-of-sata-ssds\r\n\r\nfrom(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Total_LBAs_Written\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n   |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n    |> map(fn: (r) => ({r with sata1_percent_life_remain: 100.0-(((r.RAW_value*512.0)/3500000000000000.0)*100.0)}))\r\n    |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_field\", \"_start\", \"_stop\", \"RAW_value\"])\r\n    |> rename(columns: {sata1_percent_life_remain: \"SATA1 Write Endurance Remaining\"})\r\n  |> yield()"
    },
    {
     "query": "//Micron ECO 5200 1.92TB SSD is rated for 3.5PB of write endurance  @ 512-bit sectors\r\n//SSD data sheet found here: https://www.micron.com/solutions/technical-briefs/micron-5200-series-of-sata-ssds\r\n\r\nfrom(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Total_LBAs_Written\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n   |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n    |> map(fn: (r) => ({r with sata1_percent_life_remain: 100.0-(((r.RAW_value*512.0)/3500000000000000.0)*100.0)}))\r\n    |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_field\", \"_start\", \"_stop\", \"RAW_value\"])\r\n    |> rename(columns: {sata1_percent_life_remain: \"SATA2 Write Endurance Remaining\"})\r\n  |> yield()"
    },
    {
     "query": "//Micron ECO 5200 1.92TB SSD is rated for 3.5PB of write endurance @ 512-bit sectors\r\n//SSD data sheet found here: https://www.micron.com/solutions/technical-briefs/micron-5200-series-of-sata-ssds\r\n\r\nfrom(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Total_LBAs_Written\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n   |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n    |> map(fn: (r) => ({r with sata1_percent_life_remain: 100.0-(((r.RAW_value*512.0)/3500000000000000.0)*100.0)}))\r\n    |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_field\", \"_start\", \"_stop\", \"RAW_value\"])\r\n    |> rename(columns: {sata1_percent_life_remain: \"SATA3 Write Endurance Remaining\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Bytes Written",
   "type": "timeseries",
   "description": "Endurance (TBW in PB) for Micron 5200 ECO is 3.5 Peta-Bytes",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "query": "//Micron ECO 5200 1.92TB SSD is rated for 3.5PB of write endurance @ 512-bit sectors\r\n//SSD data sheet found here: https://www.micron.com/solutions/technical-briefs/micron-5200-series-of-sata-ssds\r\n\r\nfrom(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Total_LBAs_Written\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n   |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n    |> map(fn: (r) => ({r with sata1_percent_life_remain: (r.RAW_value*512.0)}))\r\n    |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_field\", \"_start\", \"_stop\", \"RAW_value\"])\r\n    |> rename(columns: {sata1_percent_life_remain: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "//Micron ECO 5200 1.92TB SSD is rated for 3.5PB of write endurance @ 512-bit sectors\r\n//SSD data sheet found here: https://www.micron.com/solutions/technical-briefs/micron-5200-series-of-sata-ssds\r\n\r\nfrom(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Total_LBAs_Written\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n   |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n    |> map(fn: (r) => ({r with sata1_percent_life_remain: (r.RAW_value*512.0)}))\r\n    |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_field\", \"_start\", \"_stop\", \"RAW_value\"])\r\n    |> rename(columns: {sata1_percent_life_remain: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "//Micron ECO 5200 1.92TB SSD is rated for 3.5PB of write endurance @ 512-bit sectors\r\n//SSD data sheet found here: https://www.micron.com/solutions/technical-briefs/micron-5200-series-of-sata-ssds\r\n\r\nfrom(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Total_LBAs_Written\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n   |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n    |> map(fn: (r) => ({r with sata1_percent_life_remain: (r.RAW_value*512.0)}))\r\n    |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_field\", \"_start\", \"_stop\", \"RAW_value\"])\r\n    |> rename(columns: {sata1_percent_life_remain: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Write Amplification Factor",
   "type": "timeseries",
   "description": "Write amplification factor (WAF) is a numerical value that represents the amount of data a solid state storage controller has to write in relation to the amount of data that the host’s flash controller has to write.  The numerical value is calculated as a rate by dividing the amount of data written to flash media by the amount of data written by the host.\n\nA write amplification factor of 1 means that 1GB of data was written to the flash host media and the host’s flash controller also wrote 1GB.  A write factor of 1 is ideal, but occurs less frequently as the media gets used and the number of program/erase (P/E) cycles increases.  Program/erase cycles are managed by the device's flash controller, which uses a logical to physical mapping system known as logical block addressing (LBA) to manage data. When data is rewritten, the flash controller writes the new data in a different location and then updates the LBA with the new location. Invalid data continues to reside in the old location and those cells must be erased before they can be written to again. Because each cell can only tolerate a finite number of program/erase cycles before becoming unreliable, the higher the write amplification factor, the closer the media is to end-of-life.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 72 },
   "targets": [
    {
     "query": "Host_Program_Page_Count=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Host_Program_Page_Count\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_start\", \"_stop\"])\r\n\r\n\r\nBckgnd_Program_Page_Cnt=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Bckgnd_Program_Page_Cnt\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n    |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_start\", \"_stop\"])\r\n\r\njoin(tables: {Bckgnd_Program_Page_Cnt: Bckgnd_Program_Page_Cnt, Host_Program_Page_Count: Host_Program_Page_Count}, on: [\"_time\",\"_field\"])\r\n    |> map(fn: (r) => ({r with sata1_percent_life_remain: ((r._value_Host_Program_Page_Count + r._value_Bckgnd_Program_Page_Cnt)/r._value_Host_Program_Page_Count)}))\r\n   |> drop(columns: [\"_value_Host_Program_Page_Count\",\"_value_Bckgnd_Program_Page_Cnt\",\"_value_Reallocated_Sector_Ct\",\"_value_Unused_Rsvd_Blk_Cnt_Tot\", \"_field\"])\r\n   |> rename(columns: {sata1_percent_life_remain: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "Host_Program_Page_Count=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Host_Program_Page_Count\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_start\", \"_stop\"])\r\n\r\n\r\nBckgnd_Program_Page_Cnt=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Bckgnd_Program_Page_Cnt\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n    |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_start\", \"_stop\"])\r\n\r\njoin(tables: {Bckgnd_Program_Page_Cnt: Bckgnd_Program_Page_Cnt, Host_Program_Page_Count: Host_Program_Page_Count}, on: [\"_time\",\"_field\"])\r\n    |> map(fn: (r) => ({r with sata1_percent_life_remain: ((r._value_Host_Program_Page_Count + r._value_Bckgnd_Program_Page_Cnt)/r._value_Host_Program_Page_Count)}))\r\n   |> drop(columns: [\"_value_Host_Program_Page_Count\",\"_value_Bckgnd_Program_Page_Cnt\",\"_value_Reallocated_Sector_Ct\",\"_value_Unused_Rsvd_Blk_Cnt_Tot\", \"_field\"])\r\n   |> rename(columns: {sata1_percent_life_remain: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "Host_Program_Page_Count=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Host_Program_Page_Count\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_start\", \"_stop\"])\r\n\r\n\r\nBckgnd_Program_Page_Cnt=from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Bckgnd_Program_Page_Cnt\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n    |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_start\", \"_stop\"])\r\n\r\njoin(tables: {Bckgnd_Program_Page_Cnt: Bckgnd_Program_Page_Cnt, Host_Program_Page_Count: Host_Program_Page_Count}, on: [\"_time\",\"_field\"])\r\n    |> map(fn: (r) => ({r with sata1_percent_life_remain: ((r._value_Host_Program_Page_Count + r._value_Bckgnd_Program_Page_Cnt)/r._value_Host_Program_Page_Count)}))\r\n   |> drop(columns: [\"_value_Host_Program_Page_Count\",\"_value_Bckgnd_Program_Page_Cnt\",\"_value_Reallocated_Sector_Ct\",\"_value_Unused_Rsvd_Blk_Cnt_Tot\", \"_field\"])\r\n   |> rename(columns: {sata1_percent_life_remain: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Bckgnd Program Page Cnt",
   "type": "timeseries",
   "description": "Average erase count of all good blocks. \nalso known as \"FTL Program Page Count\" Number of NAND pages written by the FTL.\n\nThis value stores the cumulative FTL program page count. This attribute tracks the\nnumber of NAND pages programed by the FTL which are in addition to operations programed by the host. Write amplification factor can be calculated by WAF = (Attrib_247 +\nAttrib_248) / Attrib_247.\n\nWAF = (Host Program Page Count + FTL Program Page Count) / Host Program Page Count",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Bckgnd_Program_Page_Cnt\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Bckgnd_Program_Page_Cnt\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Bckgnd_Program_Page_Cnt\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Host_Program_Page_Count",
   "type": "timeseries",
   "description": "Number of NAND pages of data written by the host",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Host_Program_Page_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Host_Program_Page_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Host_Program_Page_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Reallocated_Sector_Ct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 93 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Reallocated_Sector_Ct\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Reallocated_Sector_Ct\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Reallocated_Sector_Ct\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Reserved_Block_Pct",
   "type": "timeseries",
   "description": "This value is the number of reserved blocks that have been used on the drive",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 100 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Reserved_Block_Pct\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Reserved_Block_Pct\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Reserved_Block_Pct\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Reallocated_Event_Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 107 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Reallocated_Event_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Reallocated_Event_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Reallocated_Event_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Erase_Fail_Count",
   "type": "timeseries",
   "description": "This value contains the raw number of ERASE failure events over the lifetime of the device.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 114 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Erase_Fail_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Erase_Fail_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Erase_Fail_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Avg Block Erase Count",
   "type": "timeseries",
   "description": "Average erase count of all good blocks",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 121 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Avg_Block-Erase_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Avg_Block-Erase_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Avg_Block-Erase_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Command Timeout",
   "type": "timeseries",
   "description": "Upon any HRESET, COMRESET, SRST: adds ac\n\nThis counter is incremented by the number of outstanding commands when the host\nissues a soft reset or a comreset. If the value ever exceeds FFFFFFFFFFFFh, it wraps\naround.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 128 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Command_Timeout\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Command_Timeout\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Command_Timeout\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "End-to-End_Error",
   "type": "timeseries",
   "description": "hat after transferring through the cache RAM data buffer, the parity data between the host and the hard drive did not match.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 135 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"End-to-End_Error\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"End-to-End_Error\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"End-to-End_Error\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Hardware_ECC_Recovered",
   "type": "timeseries",
   "description": "Tracks the total number of bits corrected over the lifetime of\nthe device",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 142 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Hardware_ECC_Recovered\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Hardware_ECC_Recovered\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Hardware_ECC_Recovered\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Offline_Uncorrectable",
   "type": "timeseries",
   "description": "Uncorrectable error count detected during SMART offline scan\n\nThis value is the cumulative number of unrecoverable read errors found in a background media scan.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 149 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Offline_Uncorrectable\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Offline_Uncorrectable\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Offline_Uncorrectable\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Power_Cycle_Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 156 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Power_Cycle_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Power_Cycle_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Power_Cycle_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Power_On_Days",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 163 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Power_On_Hours\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n   |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n    |> map(fn: (r) => ({r with SATA1: (r.RAW_value/24.0)}))\r\n    |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_field\", \"_start\", \"_stop\", \"RAW_value\"])\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Power_On_Hours\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n   |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n    |> map(fn: (r) => ({r with SATA2: (r.RAW_value/24.0)}))\r\n    |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_field\", \"_start\", \"_stop\", \"RAW_value\"])\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Power_On_Hours\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n   |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n    |> map(fn: (r) => ({r with SATA3: (r.RAW_value/24.0)}))\r\n    |> drop(columns: [\"_measurement\",\"nas_name\", \"disk_path\", \"smart_attribute\", \"_field\", \"_start\", \"_stop\", \"RAW_value\"])\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Program_Fail_Count",
   "type": "timeseries",
   "description": "Number of NAND program status failures",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 170 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Program_Fail_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Program_Fail_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Program_Fail_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "RAIN_Success_Recovered",
   "type": "timeseries",
   "description": "The total number of translation units (TU) successfully recovered by Micron's redundant array of independent NAND (RAIN) technology; increments when RAIN successfully recovers user data.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 177 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"RAIN_Success_Recovered\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"RAIN_Success_Recovered\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"RAIN_Success_Recovered\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Raw_Read_Error_Rate",
   "type": "timeseries",
   "description": "Raw correctable and uncorrectable read error rate",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 184 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Raw_Read_Error_Rate\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Raw_Read_Error_Rate\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Raw_Read_Error_Rate\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "SATA_Int_Downshift_Ct",
   "type": "timeseries",
   "description": "Represents the total number of host interface speed downshifts on the SATA link. For\nexample, the SATA link shifts to a lower-generation speed (1.5 Gb/s or 3.0 Gb/s) than\nwhat was previously negotiated (6 Gb/s).",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 191 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"SATA_Int_Downshift_Ct\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"SATA_Int_Downshift_Ct\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"SATA_Int_Downshift_Ct\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "UDMA_CRC_Error_Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 198 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"UDMA_CRC_Error_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"UDMA_CRC_Error_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"UDMA_CRC_Error_Count\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Unexpect_Power_Loss_Ct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 205 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Unexpect_Power_Loss_Ct\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Unexpect_Power_Loss_Ct\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Unexpect_Power_Loss_Ct\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  },
  {
   "title": "Unused_Rsvd_Blk_Cnt_Tot",
   "type": "timeseries",
   "description": "Nominal number is 6718 for a Micron 5200 ECO 1.92TB SSD",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 212 },
   "targets": [
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata1\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Unused_Rsvd_Blk_Cnt_Tot\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA1\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata2\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Unused_Rsvd_Blk_Cnt_Tot\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA2\"})\r\n  |> yield()"
    },
    {
     "query": "from(bucket: \"Test/autogen\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"synology_SMART_status2\")\r\n  |> filter(fn: (r) => r[\"nas_name\"] == \"Server-Plex\")\r\n  |> filter(fn: (r) => r[\"disk_path\"] == \"/dev/sata3\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"RAW_value\")\r\n  |> filter(fn: (r) => r[\"smart_attribute\"] == \"Unused_Rsvd_Blk_Cnt_Tot\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> drop(columns: [\"_field\",\"_measurement\",\"nas_name\",\"disk_path\",\"smart_attribute\",\"_start\",\"_stop\"])\r\n   |> rename(columns: {_value: \"SATA3\"})\r\n  |> yield()"
    }
   ]
  }
 ]
}